# These are supported funding model platforms

github: RafaBlockDev # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
ethereum-address: 0xfa4D43fE35C2ce463042D04888C10C8E3AF180A5
solana-address: Gw86aZDPisqqXUTmcqbMa6ZsUvYaYAzG3gemkGiAjVxD
polygon-address: 0xfa4D43fE35C2ce463042D04888C10C8E3AF180A5

